<a href="https://colab.research.google.com/github/DawamAssidiq/proactive/blob/main/proactive.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6], float)

In [3]:
a

array([1., 2., 3., 4., 5., 6.])

In [4]:
type(a)

numpy.ndarray

In [6]:
print (a)

[1. 2. 3. 4. 5. 6.]


In [10]:
a[:2]
a[5]
a[0] = 8
a

array([8., 2., 3., 4., 5., 6.])

In [11]:
a = np.array([[1,2,3,4,5],[6,7,8,9,10]],float)
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [12]:
a[0,0]

1.0

In [13]:
a[0,1]

2.0

In [14]:
a = np.array([[1,2,3],[4,5,6]], float)
a[1,:]

array([4., 5., 6.])

In [15]:
a[:, 2]

array([3., 6.])

In [16]:
a[-1:, -2:]

array([[5., 6.]])